### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mckenzieharriman** [mckenzieharriman/markdown-portfolio#1]
- [x] Create a task list
- [ ] Turn on Github Pages
- [x] Add Headers
- [x] Merge Headers
- [x] Add an image
- [x] add a profile link
- [x] Merge your image and link
- [x] add a list
- [x] Use emphasis
- [x] Merge lists and emphasis
